<?php

return [
    'statuses' => [
        'draft' => [
            'label' => 'Draft',
            'color' => 'secondary',
            'icon' => 'bi-pencil-square',
        ],
        'final' => [
            'label' => 'Final',
            'color' => 'success',
            'icon' => 'bi-check-circle',
        ],
        'cancelled' => [
            'label' => 'Cancelled',
            'color' => 'danger',
            'icon' => 'bi-x-circle',
        ],
    ],

    'date_filters' => [
        'today' => 'Today',
        'this_week' => 'This Week',
        'last_week' => 'Last Week',
        'this_month' => 'This Month',
        'last_month' => 'Last Month',
        'last_3_months' => 'Last 3 Months',
        'this_year' => 'This Year',
        'all_months' => 'All Months',
        'custom' => 'Custom',
    ],

    'company' => [
        'name' => 'N B LOGISTICS',
        'tagline' => 'Fleet Owner & Transport Contractor',
        'address' => 'Patel Chowk, G.I.D.C. Phase - 2, Dared, Jamnagar - Gujarat - 361004',
        'city_state' => 'Jamnagar, Gujarat',
        'pin_code' => '361004',
        'mobile' => '9924328424',
        'alt_mobile' => '8401663180',
        'pan' => 'GNWPS1050M',
        'gst' => 'GNWPS1050M',
        'bank_name' => 'HDFC BANK, DARED BRANCH',
        'bank_account_name' => 'N B LOGISTICS',
        'bank_account_no' => '50200074315971',
        'bank_ifsc' => 'HDFC0004482',
    ],

    'documents' => [
        'bilty' => [
            'label' => 'Bilty',
            'route_prefix' => 'builty',
            'template_view' => 'admin.bilty.template',
            'list_title' => 'Bilty List',
            'page_title' => 'Bilty',
            'number_prefix' => 'NB-LR',
            'fields' => [
                ['name' => 'lr_number', 'label' => 'LR Number', 'type' => 'text', 'required' => true, 'source' => 'trip.lr_number', 'column' => 'col-md-6'],
                ['name' => 'lr_date', 'label' => 'LR Date', 'type' => 'date', 'required' => true, 'source' => 'trip.start_date', 'column' => 'col-md-6'],
                ['name' => 'vehicle_no', 'label' => 'Vehicle Number', 'type' => 'text', 'required' => true, 'source' => 'trip.truck_number', 'column' => 'col-md-6'],
                ['name' => 'bilty_from', 'label' => 'From', 'type' => 'text', 'required' => true, 'source' => 'trip.origin', 'column' => 'col-md-6'],
                ['name' => 'bilty_to', 'label' => 'To', 'type' => 'text', 'required' => true, 'source' => 'trip.destination', 'column' => 'col-md-6'],
                ['name' => 'consignor_name', 'label' => 'Consignor Name', 'type' => 'text', 'required' => true, 'source' => 'trip.party_name', 'column' => 'col-md-6'],
                ['name' => 'consignor_address', 'label' => 'Consignor Address', 'type' => 'textarea', 'source' => 'trip.party_address', 'column' => 'col-md-6'],
                ['name' => 'consignor_mobile', 'label' => 'Consignor Mobile', 'type' => 'text', 'source' => 'trip.party_mobile', 'column' => 'col-md-4'],
                ['name' => 'consignor_gst', 'label' => 'Consignor GST', 'type' => 'text', 'source' => 'trip.party_gst', 'column' => 'col-md-4'],
                ['name' => 'gst_paid_by', 'label' => 'GST Paid By', 'type' => 'select', 'options' => ['consignor' => 'Consignor', 'consignee' => 'Consignee'], 'column' => 'col-md-4'],
                ['name' => 'consignee_name', 'label' => 'Consignee Name', 'type' => 'text', 'required' => true, 'column' => 'col-md-6'],
                ['name' => 'consignee_address', 'label' => 'Consignee Address', 'type' => 'textarea', 'column' => 'col-md-6'],
                ['name' => 'consignee_mobile', 'label' => 'Consignee Mobile', 'type' => 'text', 'column' => 'col-md-4'],
                ['name' => 'consignee_gst', 'label' => 'Consignee GST', 'type' => 'text', 'column' => 'col-md-4'],
                ['name' => 'bilty_invoice_no', 'label' => 'Invoice No.', 'type' => 'text', 'column' => 'col-md-4'],
                ['name' => 'description_of_goods', 'label' => 'Description of Goods', 'type' => 'textarea', 'source' => 'trip.material_name', 'column' => 'col-md-6'],
                ['name' => 'no_of_packages', 'label' => 'No. of Packages', 'type' => 'number', 'column' => 'col-md-3'],
                ['name' => 'actual_weight', 'label' => 'Actual Weight', 'type' => 'text', 'column' => 'col-md-3'],
                ['name' => 'charged_weight', 'label' => 'Charged Weight', 'type' => 'text', 'column' => 'col-md-3'],
                ['name' => 'bilty_freight_amount', 'label' => 'Freight Amount', 'type' => 'number', 'required' => true, 'source' => 'trip.freight_amount', 'column' => 'col-md-3'],
                ['name' => 'hamali_charges', 'label' => 'Hamali Charges', 'type' => 'number', 'column' => 'col-md-3'],
                ['name' => 'bilty_charges', 'label' => 'Bilty Charges', 'type' => 'number', 'column' => 'col-md-3'],
                ['name' => 'advance_amount', 'label' => 'Advance Amount', 'type' => 'number', 'source' => 'trip.advance_amount', 'column' => 'col-md-3'],
                ['name' => 'eway_bill_no', 'label' => 'E-Way Bill No.', 'type' => 'text', 'column' => 'col-md-4'],
                ['name' => 'invoice_value', 'label' => 'Invoice Value', 'type' => 'number', 'column' => 'col-md-4'],
                ['name' => 'bilty_rate', 'label' => 'Rate', 'type' => 'number', 'source' => 'trip.per_unit_amount', 'column' => 'col-md-4'],
                ['name' => 'bilty_remark', 'label' => 'Remark', 'type' => 'textarea', 'source' => 'trip.note', 'column' => 'col-md-12'],
                ['name' => 'bilty_total', 'label' => 'Total Amount', 'type' => 'number', 'readonly' => true, 'column' => 'col-md-4'],
            ],
        ],
        'invoice' => [
            'label' => 'Invoice',
            'route_prefix' => 'invoices',
            'template_view' => 'admin.bill.template',
            'list_title' => 'Invoice List',
            'page_title' => 'Invoice',
            'number_prefix' => 'NB-INV',
            'fields' => [
                ['name' => 'invoice_number', 'label' => 'Invoice Number', 'type' => 'text', 'required' => true, 'source' => 'document_number', 'column' => 'col-md-6'],
                ['name' => 'invoice_date', 'label' => 'Invoice Date', 'type' => 'date', 'required' => true, 'source' => 'trip.start_date', 'column' => 'col-md-6'],
                ['name' => 'inv_vehicle_no', 'label' => 'Vehicle Number', 'type' => 'text', 'required' => true, 'source' => 'trip.truck_number', 'column' => 'col-md-6'],
                ['name' => 'inv_lr_no', 'label' => 'LR Number', 'type' => 'text', 'source' => 'trip.lr_number', 'column' => 'col-md-6'],
                ['name' => 'inv_from', 'label' => 'From', 'type' => 'text', 'required' => true, 'source' => 'trip.origin', 'column' => 'col-md-6'],
                ['name' => 'inv_to', 'label' => 'To', 'type' => 'text', 'required' => true, 'source' => 'trip.destination', 'column' => 'col-md-6'],
                ['name' => 'bill_to_name', 'label' => 'Bill To Name', 'type' => 'text', 'required' => true, 'source' => 'trip.party_name', 'column' => 'col-md-6'],
                ['name' => 'bill_to_address', 'label' => 'Bill To Address', 'type' => 'textarea', 'source' => 'trip.party_address', 'column' => 'col-md-6'],
                ['name' => 'bill_to_gst', 'label' => 'Bill To GST', 'type' => 'text', 'source' => 'trip.party_gst', 'column' => 'col-md-4'],
                ['name' => 'bill_to_city_state', 'label' => 'Bill To City / State', 'type' => 'text', 'column' => 'col-md-4'],
                ['name' => 'bill_to_pin', 'label' => 'Bill To Pin', 'type' => 'text', 'column' => 'col-md-4'],
                ['name' => 'bill_from_name', 'label' => 'Bill From Name', 'type' => 'text', 'source' => 'company.name', 'column' => 'col-md-6', 'readonly' => true],
                ['name' => 'bill_from_address', 'label' => 'Bill From Address', 'type' => 'textarea', 'source' => 'company.address', 'column' => 'col-md-6', 'readonly' => true],
                ['name' => 'bill_from_gst', 'label' => 'Bill From GST', 'type' => 'text', 'source' => 'company.gst', 'column' => 'col-md-4', 'readonly' => true],
                ['name' => 'bill_from_city_state', 'label' => 'Bill From City / State', 'type' => 'text', 'source' => 'company.city_state', 'column' => 'col-md-4', 'readonly' => true],
                ['name' => 'bill_from_pin', 'label' => 'Bill From Pin', 'type' => 'text', 'source' => 'company.pin_code', 'column' => 'col-md-4', 'readonly' => true],
                ['name' => 'bill_from_mobile', 'label' => 'Bill From Mobile', 'type' => 'text', 'source' => 'company.mobile', 'column' => 'col-md-4', 'readonly' => true],
                ['name' => 'ship_to_name', 'label' => 'Ship To Name', 'type' => 'text', 'source' => 'trip.consignee_name', 'column' => 'col-md-6'],
                ['name' => 'ship_to_address', 'label' => 'Ship To Address', 'type' => 'textarea', 'source' => 'trip.consignee_address', 'column' => 'col-md-6'],
                ['name' => 'ship_to_gst', 'label' => 'Ship To GST', 'type' => 'text', 'source' => 'trip.consignee_gst', 'column' => 'col-md-4'],
                ['name' => 'ship_to_city_state', 'label' => 'Ship To City / State', 'type' => 'text', 'column' => 'col-md-4'],
                ['name' => 'ship_to_pin', 'label' => 'Ship To Pin', 'type' => 'text', 'column' => 'col-md-4'],
                ['name' => 'ship_to_mobile', 'label' => 'Ship To Mobile', 'type' => 'text', 'source' => 'trip.consignee_mobile', 'column' => 'col-md-4'],
                ['name' => 'inv_freight_amount', 'label' => 'Freight Amount', 'type' => 'number', 'required' => true, 'source' => 'trip.freight_amount', 'column' => 'col-md-4'],
                ['name' => 'loading_charge', 'label' => 'Loading Charge', 'type' => 'number', 'column' => 'col-md-4'],
                ['name' => 'unloading_charge', 'label' => 'Unloading Charge', 'type' => 'number', 'column' => 'col-md-4'],
                ['name' => 'sgst_percent', 'label' => 'SGST %', 'type' => 'number', 'column' => 'col-md-3'],
                ['name' => 'cgst_percent', 'label' => 'CGST %', 'type' => 'number', 'column' => 'col-md-3'],
                ['name' => 'inv_description_of_goods', 'label' => 'Description of Goods', 'type' => 'textarea', 'source' => 'trip.material_name', 'column' => 'col-md-6'],
                ['name' => 'inv_remark', 'label' => 'Remark', 'type' => 'textarea', 'source' => 'trip.note', 'column' => 'col-md-6'],
                ['name' => 'payment_paid_by', 'label' => 'Payment Paid By', 'type' => 'select', 'options' => ['cash' => 'Cash', 'cheque' => 'Cheque', 'upi' => 'UPI', 'bank_transfer' => 'Bank Transfer'], 'column' => 'col-md-4'],
                ['name' => 'inv_eway_bill_no', 'label' => 'E-Way Bill No.', 'type' => 'text', 'column' => 'col-md-4'],
                ['name' => 'inv_no_of_articles', 'label' => 'No. of Articles', 'type' => 'number', 'source' => 'trip.no_of_packages', 'column' => 'col-md-4'],
                ['name' => 'inv_total_weight', 'label' => 'Total Weight', 'type' => 'text', 'source' => 'trip.actual_weight', 'column' => 'col-md-4'],
                ['name' => 'sub_total', 'label' => 'Sub Total', 'type' => 'number', 'readonly' => true, 'column' => 'col-md-4'],
                ['name' => 'sgst_amount', 'label' => 'SGST Amount', 'type' => 'number', 'readonly' => true, 'column' => 'col-md-4'],
                ['name' => 'cgst_amount', 'label' => 'CGST Amount', 'type' => 'number', 'readonly' => true, 'column' => 'col-md-4'],
                ['name' => 'grand_total', 'label' => 'Grand Total', 'type' => 'number', 'readonly' => true, 'column' => 'col-md-4'],
            ],
        ],
    ],
];
